language: cpp

matrix:
  include:

  - env:
    - OCPN_TARGET=xenial
    dist: xenial
    compiler: gcc
    script:
    - "./ci/generic-build-debian.sh"
  - env:
    - OCPN_TARGET=trusty
    dist: trusty
    compiler: gcc
    script:
    - "./ci/generic-build-debian.sh"
  - env:
    - OCPN_TARGET=osx
    os: osx
    osx_image: xcode10.2
    compiler: clang
    script:
    - "./ci/generic-build-macos.sh"
  - env:
    - OCPN_TARGET=mingw
    services:
    - docker
    script:
    - "./ci/travis-build-mingw.sh"

before_install:
- 'echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne ''/-BEGIN
  CERTIFICATE-/,/-END CERTIFICATE-/p'' | sudo tee -a /etc/ssl/certs/ca '
deploy:
  provider: script
  skip_cleanup: true
  script: ci/generic-upload.sh
  on:
    branch: master
    tags: false
notifications:
  email: false
git:
  depth: 10
addons:
  coverity_scan:
    project:
      name: OpenCPN/OpenCPN
    notification_email: pavel@kalian.cz
    build_command_prepend: mkdir -p build; cd build; cmake ..; make clean
    build_command: make
    branch_pattern: coverity_scan

branches:
  only:
    - master
    - plugins
    - plugins-build
    - plug-mgr

